Feature/improve toc scroll
lblod/ember-rdfa-editor-lblod-plugins pull request #127
Opened 2023-03-28 09:45 UTC by lagartoverde

I don't really like the solution to be honest because it involves a magic number and it has to be individually configured for every environment the editor runs on. Furthermore it has to change if the height of the topbar changes, but at least is better than before, and we can always run the previous behaviour if not configured.
As this was timeboxed I didn't want to really go further but this can be improved by maybe calculating this magic number in any way, but I don't know how right now

2023-03-28 09:46 UTC, lagartoverde commented
I tested on GN and for example the magic number has to change to 200 but otherwise it works perfectly fine

2023-03-28 09:48 UTC, lagartoverde commented
Solves https://binnenland.atlassian.net/browse/GN-4200

2023-04-04 08:02 UTC, abeforgit requested changes
I have to click twice on the ToC to scroll to the section now. That's a regression

2023-04-04 14:29 UTC, lagartoverde commented on addon/components/table-of-contents-plugin/ember-nodes/table-of-contents.ts
> +          const sayContainer = document.getElementsByClassName(
Yes, that was something I forgot to update to be honest, done now 👍

2023-04-04 14:30 UTC, lagartoverde commented
> I have to click twice on the ToC to scroll to the section now. That's a regression


Seems like is not a regression as I can reproduce on master, likely something weird happening with the prosemirror selections will have a look

2023-04-07 11:34 UTC, merged