GN-4220: Generic RDFA insert
lblod/ember-rdfa-editor-lblod-plugins pull request #145
Opened 2023-06-01 09:26 UTC by dkozickis

First iteration on https://binnenland.atlassian.net/browse/GN-4220 (Generic rdfa variables input plugin), allows to insert RDFA as "plain" HTML.

Exploring folder-tree UI as next step. 

https://github.com/lblod/ember-rdfa-editor-lblod-plugins/assets/769698/7a28aaaf-95a8-416a-b0be-fd5199fa1e11

2023-06-01 13:19 UTC, lagartoverde requested changes
Looks good to me, but I'm having some problems with the placement of the suggestions, they appear on the bottom of the modal for me
<img width="1552" alt="Screenshot 2023-06-01 at 15 17 09" src="https://github.com/lblod/ember-rdfa-editor-lblod-plugins/assets/17006446/e5859272-da92-4694-9937-54edb907ec51">

2023-06-05 07:38 UTC, elpoelma requested changes
Seems to work well overall :) Just a small note.

2023-06-05 07:38 UTC, elpoelma commented on addon/components/generic-rdfa-variable/insert-menu.hbs
> +  @disabled={{this.disabled}}
The `disabled` property does not seem to be defined in the backing class.

2023-06-06 13:08 UTC, abeforgit requested changes
when opening the modal, the codemirror editor is not focused
when closing the modal (in any way), the editor is not refocused

2023-06-07 14:36 UTC, merged