GN-4258: Number variable - support min/max
lblod/ember-rdfa-editor-lblod-plugins pull request #147
Opened 2023-06-08 10:59 UTC by dkozickis

https://binnenland.atlassian.net/browse/GN-4258

https://github.com/lblod/ember-rdfa-editor-lblod-plugins/assets/769698/71bcb49b-3b60-4742-a209-c1387ca44421

- Tests (lint) currently failing because of failure in upstream PR #142

2023-06-09 10:05 UTC, lagartoverde requested changes
Looks good to me overall, just left some minor comments, I don't like the name extra attributes but I don't have a better one, I just think we should use the data- atttributes instead of writting it as extraattributes in the exported HTML

2023-06-09 10:05 UTC, lagartoverde commented on addon/components/variable-plugin/number-settings.hbs
> +  <div class='to'><span>tot</span></div>
tot should also be translated :)

2023-06-09 10:05 UTC, lagartoverde commented on addon/plugins/variable-plugin/utils/constants.ts
> +export const EXTRA_ATTRIBUTES_KEY = 'extraAttributes';
maybe the extra attributes should be written to the html in the data- attributes

2023-06-09 11:45 UTC, x-m-el commented
I'm not sure if I'm looking at the code wrong, but why is "EXTRA_ATTRIBUTES_KEY" needed?
I know the whole variable structure is a bit of a mess (see [GN-4346](https://binnenland.atlassian.net/browse/GN-4346) ), and this feels like trying to maybe partially fix this, but it doesn't feel like the correct way.

I think it'd be better to add the min and max as separate attributes (if using `data-` is a convention for this stuff, could be called data-min and data-max).
This will of course only be used by a number variable, but it will just be empty (and not used) by other variables, which I think is fine.

2023-06-09 11:46 UTC, x-m-el reviewed
I'm not sure if I'm looking at the code wrong, but why is "EXTRA_ATTRIBUTES_KEY" needed?
I know the whole variable structure is a bit of a mess (see [GN-4346](https://binnenland.atlassian.net/browse/GN-4346) ), and this feels like trying to maybe partially fix this, but it doesn't feel like the correct way.

I think it'd be better to add the min and max as separate attributes (if using `data-` is a convention for this stuff, could be called `data-min` and `data-max`).
This will of course only be used by a number variable, but it will just be empty (and not used) by other variables, which I think is fine (not the best, but again, this is because it needs to be split up in the future anyway).

2023-06-12 13:52 UTC, lagartoverde commented
Looks good to me, but still I would rather it be written as `data-minimumvalue` instead of `minimumvalue`

2023-06-13 09:32 UTC, lagartoverde approved these changes

2023-06-13 09:44 UTC, elpoelma requested changes
Looks good overall, but still noticed some issues

2023-06-13 09:44 UTC, elpoelma commented on addon/plugins/variable-plugin/nodes.ts
> +          const label = node.getAttribute('dataLabel');
This should be `node.getAttribute('data-label');`. Alternatively, you can also use `node.dataset.label`

2023-06-13 10:29 UTC, merged