GN-4404: Made the number variable also show placeholders
lblod/ember-rdfa-editor-lblod-plugins pull request #186
Opened 2023-06-30 12:28 UTC by lagartoverde

### Overview
Reworked the variable plugin to show the placeholder nummer when no number was inserted

##### connected issues and PRs:
[jira ticket](https://binnenland.atlassian.net/browse/GN-4404?atlOrigin=eyJpIjoiZTA0YmM3YTAwNWNhNDA5YTlmZjJiMTNlNTI4ZDEyYzYiLCJwIjoiaiJ9)

### Setup
none

### How to test/reproduce
Insert a number variable, don't fill it and then click on the show html export button, you should see nummer instead of nothing 

### Challenges/uncertainties
Currently only nummer gets written, which is correct for now, but it has to change when the document language gets implemented in https://github.com/lblod/ember-rdfa-editor/pull/872

### Checks PR readiness
- [ ] UI: works on smaller screen sizes
- [ ] UI: feedback for any loading/error states
- [ ] Check if dummy app is correctly updated
- [ ] Check cancel/go-back flows
- [ ] changelog
- [ ] npm lint
- [ ] no new deprecations

2023-06-30 20:05 UTC, abeforgit requested changes
Doesn't quite work consistently
repro in dummy: 
- add number variable (and do nothing else)
- "show export preview" -> placeholder not shown
repro in RB:
(- npm link_
- make new regulation
- add number var (and do nothing else)
- click on "save and publish"

I'm adding the "do nothing else" cause it seems as soon as you do other things it does start working.

2023-06-30 20:05 UTC, abeforgit commented on addon/plugins/variable-plugin/nodes.ts
> +      return 'nummer';
something like 'Voeg getal in' would be better

2023-07-03 09:57 UTC, elpoelma commented
> Doesn't quite work consistently repro in dummy:
> 
>     * add number variable (and do nothing else)
> 
>     * "show export preview" -> placeholder not shown
>       repro in RB:
>       (- npm link_
> 
>     * make new regulation
> 
>     * add number var (and do nothing else)
> 
>     * click on "save and publish"
> 
> 
> I'm adding the "do nothing else" cause it seems as soon as you do other things it does start working.

Should be solved now, the main issue was the distinction of having the value of the content attribute being `null` vs `undefined`

2023-07-03 12:47 UTC, abeforgit approved these changes

2023-07-03 13:02 UTC, merged