GN-4732: ensure variables are selected/focused after insertion
lblod/ember-rdfa-editor-lblod-plugins pull request #392
Opened 2024-02-27 10:07 UTC by elpoelma

### Overview
This PR introduces some changes into what happens after inserting a variable node.

**Before this PR:**
- A text-cursor is set just after the inserted variable (the variable is not focused)
- This causes different issues on both chromium and firefox
   * On chromium: no text-cursor is shown
   * On firefox: a text-cursor is shown, but does not act as a real selection (typing does not work)

**Modifications introduced in this PR:**
- After variable insertion, the variables is selected/focused, allowing users to directly interact with them
- Similar to how addresses/links behave
- Works on both firefox and chromium

##### connected issues and PRs:
Solves [GN-4732](https://binnenland.atlassian.net/browse/GN-4732?atlOrigin=eyJpIjoiYjdjNzFkYTJjMjg5NDJkZmJlODg4OGY0YzZmMjY2NjUiLCJwIjoiaiJ9)

### How to test/reproduce
- `pnpm start`
- Insert a variable (text, number, codelist, location or date)
- Notice that the variable is selected/focused after insertion, you can directly interact with them

### Checks PR readiness
- [ ] UI: works on smaller screen sizes
- [ ] UI: feedback for any loading/error states
- [ ] Check if dummy app is correctly updated
- [ ] Check cancel/go-back flows
- [ ] changelog
- [ ] npm lint
- [ ] no new deprecations

2024-02-29 20:28 UTC, abeforgit requested changes
would be even better if the placeholder inside the variables that have one would be selected, you think that's doable?

2024-03-07 11:13 UTC, elpoelma commented
> would be even better if the placeholder inside the variables that have one would be selected, you think that's doable?

That would be nice indeed:
- At the moment, this is quite hard to do, as the selection/state of the embedded editor/main editor are quite seperated
- I have some ideas to improve the integration of embedded editor, in order to ensure that selections/states are shared in a better way. In this case the selection of the main editor would also be updated when changing the selection in the embedded editor. The developer using our editor would not even need to care/be aware of the embedded editors. This approach would be similar to https://prosemirror.net/examples/codemirror/

2024-03-08 11:21 UTC, abeforgit commented
sounds good, lets merge for now then since it's already an improvement

2024-03-08 11:21 UTC, abeforgit approved these changes

2024-03-08 12:36 UTC, merged