Rework of date plugin with custom date NodeSpec
lblod/ember-rdfa-editor-lblod-plugins pull request #44
Opened 2023-01-05 16:29 UTC by elpoelma

2023-01-06 12:22 UTC, lagartoverde requested changes
Works good, I think we are missing 2 things, first of all the date gets setted to the actual time it's now, we should set the hour, minutes, seconds and ms to 0 if we are not specifing them in the modal. Second we have to modify the variable plugin to insert this new node :)

2023-01-09 09:48 UTC, elpoelma commented
> Works good, I think we are missing 2 things, first of all the date gets setted to the actual time it's now, we should set the hour, minutes, seconds and ms to 0 if we are not specifing them in the modal. Second we have to modify the variable plugin to insert this new node :)

Ok I will be looking into reworking the insert-variable plugin configuration in order to support this.

2023-01-10 15:52 UTC, abeforgit requested changes
Note I think we have to add format support before we can release this to prod, will make a jira story

2023-01-10 15:52 UTC, abeforgit commented on addon/plugins/rdfa-date-plugin/nodes/date.ts
> +      ? 'Voeg datum in'
Would be good to i18n this

2023-01-10 15:52 UTC, abeforgit commented on addon/components/rdfa-date-plugin/insert.ts
> +        this.schema.node('date', {
Would be nice to autoselect the inserted date here I think

2023-01-12 12:09 UTC, abeforgit approved these changes

2023-01-12 12:09 UTC, merged