Use the new template uris on variables
lblod/ember-rdfa-editor-lblod-plugins pull request #505
Opened 2024-11-14 14:42 UTC by lagartoverde

### Overview
When we use the variables on the final agendapoint the uris are the same, so if we insert 2 snippets with the same variable the rdfa parser does weird things with the values

##### connected issues and PRs:
GN-5232

### Setup
None

### How to test/reproduce
create a snippet in RB with variables, insert that snippet 2 times in GN, observe that the variables have different uuids on GN even if they come from the same snippet

### Challenges/uncertainties
None

### Checks PR readiness
- [x] UI: works on smaller screen sizes
- [x] UI: feedback for any loading/error states
- [x] Check if dummy app is correctly updated
- [x] Check cancel/go-back flows
- [x] changelog
- [x] npm lint
- [x] no new deprecations

2024-11-14 16:00 UTC, elpoelma commented
@lagartoverde Shouldn't we make this configurable/optional, as you don't want to use the template URIs when inserting in GN directly I would think (e.g. for addresses and dates)

2024-11-14 21:37 UTC, abeforgit commented
> @lagartoverde Shouldn't we make this configurable/optional, as you don't want to use the template URIs when inserting in GN directly I would think (e.g. for addresses and dates)

yeah that's a good idea

2024-11-15 12:26 UTC, elpoelma requested changes
Looks good overall! Some minor comments...

2024-11-15 12:26 UTC, elpoelma commented on addon/plugins/variable-plugin/recreateUuidsOnPaste.ts
> +    console.log(prop);
console.log

2024-11-15 12:26 UTC, elpoelma commented on addon/components/variable-plugin/address/utils.ts
We might also need to generate a placeholder for the `__rdfaId`, not sure though...

2024-11-15 12:26 UTC, elpoelma commented on addon/components/variable-plugin/autofilled/insert.gts
We might need to generate a template URI for the `__rdfaId` here.

2024-11-18 12:07 UTC, elpoelma commented on addon/components/variable-plugin/address/utils.ts
oh ok!

2024-11-18 12:11 UTC, elpoelma approved these changes

2024-11-18 12:17 UTC, elpoelma commented
One thing: maybe we should also add a `templateMode` to https://github.com/lblod/ember-rdfa-editor-lblod-plugins/blob/1e760301a2e9ed161bc6e19a598bb1894a3acf2d/addon/components/lmb-plugin/insert.ts

2024-11-18 13:28 UTC, merged