Check insertion/moving possibility of structures using delayed restartable tasks
lblod/ember-rdfa-editor-lblod-plugins pull request #84
Opened 2023-01-27 14:44 UTC by elpoelma

This improves the performance of the plugin, as this PR ensures that the move/insertion possibility is not checked every state change.

2023-02-01 16:24 UTC, abeforgit requested changes

2023-02-01 16:24 UTC, abeforgit commented on addon/plugins/article-structure-plugin/commands/insert-structure.ts
> +    findNodes({
can we make this configurable from the host app, and default to searching everything (aka the old behavior)?

2023-02-02 18:39 UTC, elpoelma commented
@abeforgit @lagartoverde I'm gonna put this on hold now, I'm not fully happy with the interface yet.

2023-09-19 13:47 UTC, abeforgit commented
this keeps running our ci for no reason so gonna close it (but ill leave the branch up)

2023-09-19 13:47 UTC, closed without merging